-- MySQL Script generated by MySQL Workbench
-- Sun Mar  9 15:55:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemon_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LittleLemon_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemon_DB` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemon_DB` ;

-- -----------------------------------------------------
-- Table `LittleLemon_DB`.`Customer_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon_DB`.`Customer_Details` (
  `CustomerID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `ContactNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemon_DB`.`Menu_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon_DB`.`Menu_Items` (
  `MenuItemID` INT NOT NULL,
  `CourseName` VARCHAR(45) NULL,
  `StarterName` VARCHAR(45) NULL,
  `DessertName` VARCHAR(45) NULL,
  `Menu_Itemscol` VARCHAR(45) NULL,
  PRIMARY KEY (`MenuItemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemon_DB`.`Staff_Information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon_DB`.`Staff_Information` (
  `StaffID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Salary` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`StaffID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemon_DB`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon_DB`.`Orders` (
  `OrderID` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Quantity` INT NOT NULL,
  `TotalCost` DECIMAL(10,2) NOT NULL,
  `CustomerID` INT NOT NULL,
  `MenuItemID` INT NOT NULL,
  `StaffID` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_Orders_Customer_Details_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `fk_Orders_Menu_Items1_idx` (`MenuItemID` ASC) VISIBLE,
  INDEX `fk_Orders_Staff_Information1_idx` (`StaffID` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customer_Details`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `LittleLemon_DB`.`Customer_Details` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Menu_Items1`
    FOREIGN KEY (`MenuItemID`)
    REFERENCES `LittleLemon_DB`.`Menu_Items` (`MenuItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Staff_Information1`
    FOREIGN KEY (`StaffID`)
    REFERENCES `LittleLemon_DB`.`Staff_Information` (`StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemon_DB`.`Order_Delivery_Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon_DB`.`Order_Delivery_Status` (
  `DeliveryID` INT NOT NULL,
  `Date` DATETIME NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`DeliveryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemon_DB`.`Menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon_DB`.`Menus` (
  `MenuID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Cuisine` VARCHAR(45) NULL,
  `MenuItemID` INT NOT NULL,
  PRIMARY KEY (`MenuID`),
  INDEX `fk_Menus_Menu_Items1_idx` (`MenuItemID` ASC) VISIBLE,
  CONSTRAINT `fk_Menus_Menu_Items1`
    FOREIGN KEY (`MenuItemID`)
    REFERENCES `LittleLemon_DB`.`Menu_Items` (`MenuItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemon_DB`.`Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemon_DB`.`Bookings` (
  `BookingID` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `TableNumber` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `StaffID` INT NOT NULL,
  PRIMARY KEY (`BookingID`),
  INDEX `fk_Bookings_Customer_Details1_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `fk_Bookings_Staff_Information1_idx` (`StaffID` ASC) VISIBLE,
  CONSTRAINT `fk_Bookings_Customer_Details1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `LittleLemon_DB`.`Customer_Details` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookings_Staff_Information1`
    FOREIGN KEY (`StaffID`)
    REFERENCES `LittleLemon_DB`.`Staff_Information` (`StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
